author: ${project.authors}
version: ${project.version}
name: ${project.name}
main: ${project.main}

permissions:
  salvagesmelter.createsign:
    default: op
    description: allows a player to create a [SALVAGE] Sign to attach to furnaces
  salvagesmelter.admin:
    default: op
    description: Allows reloading the config file.
  salvagesmelter.group.*:
    default: op
    description: Access to all grouped recipes. Replace * with the group name for a single group.
commands:
  salvagesmelter:
    description: Root command
    usage:
     | #keeps new lines
     /<command> reload - reload the config file.
     /<command> debug - toggle debug mode.
    permission: salvagesmelter.admin
  salvagesmelter reload:
    description: reload the config file
    usage: /<command> - reload the config file
    permission: salvagesmelter.admin
  salvagesmelter debug:
    description: toggle debug mode.
    usage: /<command> - toggle debug mode.
    permission: salvagesmelter.admin
